### ISSUE TITLE
gray() is not to spec

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-color-gray#11]
This plugin and the specification have greatly diverged. I can fix it, but it would require a rewrite of much of the functionality of this plugin.

```
gray() = gray( <number>  [ / <alpha-value> ]? )
```

https://drafts.csswg.org/css-color/#grays

---

1. The correct arguments for `gray()` are a `<number>` followed by an optional slash (`/`) and an `<alpha-value>`. Presently, this plugin supports both a `<number>` and a `<percentage>` followed by an optional comma (`,`) and an `<alpha-value>`. ([citation](https://drafts.csswg.org/css-color/#funcdef-gray))

2. The first `<number>` argument specifies a shade of gray equal to the CIE Lightness, which is typically a number between `0` (representing black) and `100` (representing white), similar to the lightness argument of `hsl()`. And while a polyfill may not support displaying brighter colors, CIE Lightness can exceed this range on some systems, with extra-bright whites using a lightness up to `400`. Presently and as pointed out in #10, this plugin specifies a shade of gray equal to the RGB Lightness, which is uses a scale of `0` (representing black) to `255` (representing white) or a percentage. These conversions are not equal. ([citation](https://drafts.csswg.org/css-color/#gray-to-rgb))

---

I will be happy to provide a re-written version of this plugin that follows the spec. However, if you would prefer that your users stick with your syntax, this is also fine, and other authors have chosen this, but I must then remove the plugin from postcss-preset-env in order to correctly reflect the specification.

**Comment by asifshirazi** [comment]
Thanks @jonathantneal. I'm waiting for 5.0.0 release :(

**Comment by jonathantneal** [comment]
Resolved by #12
