### ISSUE TITLE
Incorrect parsing of "content" property

### ISSUE THREAD

**Issue by DenVdmj** [postcss/postcss-color-gray#6]
This code causes an error:

```
function useGray() {
  return postcss().use(colorGray());
}
useGray().process('.some:after { content: "-=<)gray(>=-"; }').css;
```

And it's common problem for all post-css plugins.

**Comment by MoOx** [comment]
> And it's common problem for all post-css plugins.

True. Most plugins made during the early day of postcss were not using postcss-value-parser.

PR welcome to fix this issue(s).

**Comment by DenVdmj** [comment]
I think it needs more detailed AST. That is, it is a problem of postcss. It would be strange to do a detailed parsing of css-declarations when we already have AST.

**Comment by MoOx** [comment]
Totally.
