### ISSUE TITLE
Percent lower than 10% not working

### ISSUE THREAD

**Issue by redaxmedia** [postcss/postcss-color-gray#7]
What is working:

<pre>
gray(0, 50%)
gray(0, 0.05)
</pre>

What is not working:

<pre>
gray(0, 5%)
</pre>

This returns: Unable to parse color from string "gray(0,5%)"

**Comment by MoOx** [comment]
That's a problem indeed. PR welcome to fix it, should not be that hard.

**Comment by wc-matteo** [comment]
You can use `05%` in the meantime.
